oauth:
  kakao:
    client_id: b8f443e86b54526fbf4581f128472a06 # REST API 키
    redirect_uri: http://localhost:3000/oauth/kakao/redirect
    client_secret: XgxOQkbMnXQ2hrEZl15LrY2SM5cXiPsu # Client Secret 키
    scope: profile_nickname, profile_image